
import java.util.ArrayList;
import java.util.Random;
import javax.swing.JOptionPane;

/**
 *
 * @author gabri
 */
public class Pantalla extends javax.swing.JFrame {

    static void Mercado(Jugador jugador, Inventario inventario) {
        
    }
    
    /**
     * Creates new form Pantalla
     */
    public Pantalla() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Decision = new javax.swing.JDialog();
        jPanel2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        FacSelec = new javax.swing.JTextField();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        jLabel49 = new javax.swing.JLabel();
        jLabel50 = new javax.swing.JLabel();
        jLabel51 = new javax.swing.JLabel();
        jLabel52 = new javax.swing.JLabel();
        jLabel53 = new javax.swing.JLabel();
        jLabel54 = new javax.swing.JLabel();
        jLabel56 = new javax.swing.JLabel();
        jLabel57 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        Mapa = new javax.swing.JDialog();
        jPanel3 = new javax.swing.JPanel();
        jLabel60 = new javax.swing.JLabel();
        jLabel61 = new javax.swing.JLabel();
        MapaGen = new javax.swing.JLabel();
        MerFalso = new javax.swing.JPanel();
        jLabel76 = new javax.swing.JLabel();
        jLabel77 = new javax.swing.JLabel();
        MercadoAmplio = new javax.swing.JDialog();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel59 = new javax.swing.JLabel();
        jLabel58 = new javax.swing.JLabel();
        jLabel55 = new javax.swing.JLabel();
        Comprar = new javax.swing.JButton();
        Vender = new javax.swing.JButton();
        VenderU = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel31 = new javax.swing.JLabel();
        CompOb = new javax.swing.JDialog();
        jPanel6 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel62 = new javax.swing.JLabel();
        jLabel63 = new javax.swing.JLabel();
        jLabel64 = new javax.swing.JLabel();
        Armaduras = new javax.swing.JButton();
        Pociones = new javax.swing.JButton();
        ObMag = new javax.swing.JButton();
        ObMit = new javax.swing.JButton();
        Armas = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        jLabel66 = new javax.swing.JLabel();
        jLabel67 = new javax.swing.JLabel();
        jLabel68 = new javax.swing.JLabel();
        jLabel69 = new javax.swing.JLabel();
        jLabel70 = new javax.swing.JLabel();
        jLabel71 = new javax.swing.JLabel();
        jLabel65 = new javax.swing.JLabel();
        VendOb = new javax.swing.JDialog();
        jPanel9 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jLabel72 = new javax.swing.JLabel();
        jLabel73 = new javax.swing.JLabel();
        jLabel74 = new javax.swing.JLabel();
        jLabel75 = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        jLabel81 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        BtnInicio = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        jPanel2.setBackground(new java.awt.Color(102, 0, 0));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto_final/image006-1-no-background.png"))); // NOI18N
        jLabel7.setText("jLabel7");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 30, 210, -1));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto_final/Wintertooth.png"))); // NOI18N
        jLabel8.setText("jLabel8");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 60, 90, -1));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto_final/Bordeleaux_Errant.png"))); // NOI18N
        jLabel9.setText("jLabel9");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 60, 90, -1));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto_final/The_Western_Provinces.png"))); // NOI18N
        jLabel10.setText("jLabel10");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, 90, -1));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto_final/The_Maggot_Host.png"))); // NOI18N
        jLabel11.setText("jLabel11");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 60, 90, -1));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto_final/Exiles_of_Khorne.png"))); // NOI18N
        jLabel12.setText("jLabel12");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 60, 90, -1));

        jLabel32.setBackground(new java.awt.Color(153, 102, 0));
        jLabel32.setFont(new java.awt.Font("Roboto Medium", 1, 12)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(255, 255, 255));
        jLabel32.setText("Dwarfs");
        jPanel2.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 290, 50, 20));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto_final/Reikland.png"))); // NOI18N
        jLabel6.setText("jLabel6");
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, 90, -1));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto_final/Oracles_of_Tzeentch.png"))); // NOI18N
        jLabel13.setText("jLabel13");
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 60, 90, -1));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto_final/Seducers_of_Slaanesh.png"))); // NOI18N
        jLabel14.setText("jLabel14");
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 200, 90, -1));

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto_final/Daughters_of_the_Forest.png"))); // NOI18N
        jLabel15.setText("jLabel15");
        jPanel2.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 200, 90, -1));

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto_final/Clan_Angrund.png"))); // NOI18N
        jLabel16.setText("jLabel16");
        jPanel2.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 200, 90, -1));

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto_final/Knights_of_Caledor.png"))); // NOI18N
        jLabel17.setText("jLabel17");
        jPanel2.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 340, 90, -1));

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto_final/Shadow_Legion.png"))); // NOI18N
        jLabel18.setText("jLabel18");
        jPanel2.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 200, 80, -1));

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto_final/Harbinger_of_Disaster (1).png"))); // NOI18N
        jLabel19.setText("jLabel19");
        jPanel2.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 200, 90, -1));

        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto_final/Clan_Skryre.png"))); // NOI18N
        jLabel20.setText("jLabel20");
        jPanel2.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 340, 90, -1));

        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto_final/The_Warhost_of_Zharr.png"))); // NOI18N
        jLabel21.setText("jLabel21");
        jPanel2.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 340, 90, -1));

        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto_final/Grimgor27Ardboyz.png"))); // NOI18N
        jLabel22.setText("jLabel22");
        jPanel2.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 340, 90, -1));

        jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto_final/Wargrove_of_Woe.png"))); // NOI18N
        jLabel23.setText("jLabel23");
        jPanel2.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 340, 90, -1));

        jLabel24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto_final/Ghosts_of_Pahuax.png"))); // NOI18N
        jLabel24.setText("jLabel24");
        jPanel2.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 340, 90, -1));

        jLabel25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto_final/The_Thousand_Maws.png"))); // NOI18N
        jLabel25.setText("jLabel25");
        jPanel2.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 480, 90, -1));

        jLabel26.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto_final/Goldtooth.png"))); // NOI18N
        jLabel26.setText("jLabel26");
        jPanel2.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 480, 90, -1));

        jLabel27.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto_final/Court_of_Lybaras.png"))); // NOI18N
        jLabel27.setText("jLabel27");
        jPanel2.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 200, 90, -1));

        jLabel28.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto_final/The_Awakened.png"))); // NOI18N
        jLabel28.setText("jLabel28");
        jPanel2.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 480, 90, -1));

        jLabel29.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto_final/The_Barrow_Legion.png"))); // NOI18N
        jLabel29.setText("jLabel29");
        jPanel2.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 480, 90, -1));

        jLabel2.setFont(new java.awt.Font("Roboto Black", 2, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(153, 153, 153));
        jLabel2.setText("Para Avanzar en el Juego Debes de Seleccionar una Faccion");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 600, 330, 90));

        FacSelec.setText("Ingresa el Nombre de la Faccion Seleccionaras");
        FacSelec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FacSelecActionPerformed(evt);
            }
        });
        jPanel2.add(FacSelec, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 590, 280, -1));

        jLabel33.setBackground(new java.awt.Color(153, 102, 0));
        jLabel33.setFont(new java.awt.Font("Roboto Medium", 1, 12)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(255, 255, 255));
        jLabel33.setText("The Empire");
        jPanel2.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, 70, -1));

        jLabel34.setBackground(new java.awt.Color(153, 102, 0));
        jLabel34.setFont(new java.awt.Font("Roboto Medium", 1, 12)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(255, 255, 255));
        jLabel34.setText("Norsca");
        jPanel2.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 150, 70, -1));

        jLabel35.setBackground(new java.awt.Color(153, 102, 0));
        jLabel35.setFont(new java.awt.Font("Roboto Medium", 1, 12)); // NOI18N
        jLabel35.setForeground(new java.awt.Color(255, 255, 255));
        jLabel35.setText("Bretonnia");
        jPanel2.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 150, 70, 20));

        jLabel36.setBackground(new java.awt.Color(153, 102, 0));
        jLabel36.setFont(new java.awt.Font("Roboto Medium", 1, 12)); // NOI18N
        jLabel36.setForeground(new java.awt.Color(255, 255, 255));
        jLabel36.setText("Grand Cathay");
        jPanel2.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, 90, 20));

        jLabel37.setBackground(new java.awt.Color(153, 102, 0));
        jLabel37.setFont(new java.awt.Font("Roboto Medium", 1, 12)); // NOI18N
        jLabel37.setForeground(new java.awt.Color(255, 255, 255));
        jLabel37.setText("Tomb KIngs");
        jPanel2.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 180, 110, 20));

        jLabel38.setBackground(new java.awt.Color(153, 102, 0));
        jLabel38.setFont(new java.awt.Font("Roboto Medium", 1, 12)); // NOI18N
        jLabel38.setForeground(new java.awt.Color(255, 255, 255));
        jLabel38.setText("  Kislev");
        jPanel2.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 290, 50, 20));

        jLabel39.setBackground(new java.awt.Color(153, 102, 0));
        jLabel39.setFont(new java.awt.Font("Roboto Medium", 1, 12)); // NOI18N
        jLabel39.setForeground(new java.awt.Color(255, 255, 255));
        jLabel39.setText("High Elves");
        jPanel2.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 430, 70, 20));

        jLabel40.setBackground(new java.awt.Color(153, 102, 0));
        jLabel40.setFont(new java.awt.Font("Roboto Medium", 1, 12)); // NOI18N
        jLabel40.setForeground(new java.awt.Color(255, 255, 255));
        jLabel40.setText("Wood Elves");
        jPanel2.add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 430, 70, 20));

        jLabel41.setBackground(new java.awt.Color(153, 102, 0));
        jLabel41.setFont(new java.awt.Font("Roboto Medium", 1, 12)); // NOI18N
        jLabel41.setForeground(new java.awt.Color(255, 255, 255));
        jLabel41.setText("Lizardmen");
        jPanel2.add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 430, 70, 20));

        jLabel42.setBackground(new java.awt.Color(153, 102, 0));
        jLabel42.setFont(new java.awt.Font("Roboto Medium", 1, 12)); // NOI18N
        jLabel42.setForeground(new java.awt.Color(255, 255, 255));
        jLabel42.setText("  Khorne");
        jPanel2.add(jLabel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 140, 70, 20));

        jLabel43.setBackground(new java.awt.Color(153, 102, 0));
        jLabel43.setFont(new java.awt.Font("Roboto Medium", 1, 12)); // NOI18N
        jLabel43.setForeground(new java.awt.Color(255, 255, 255));
        jLabel43.setText("    Nurgle");
        jPanel2.add(jLabel43, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 140, 70, 20));

        jLabel44.setBackground(new java.awt.Color(153, 102, 0));
        jLabel44.setFont(new java.awt.Font("Roboto Medium", 1, 12)); // NOI18N
        jLabel44.setForeground(new java.awt.Color(255, 255, 255));
        jLabel44.setText("Tzeentch");
        jPanel2.add(jLabel44, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 140, 70, 20));

        jLabel45.setBackground(new java.awt.Color(153, 102, 0));
        jLabel45.setFont(new java.awt.Font("Roboto Medium", 1, 12)); // NOI18N
        jLabel45.setForeground(new java.awt.Color(255, 255, 255));
        jLabel45.setText("Slaanesh");
        jPanel2.add(jLabel45, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 290, 70, 20));

        jLabel46.setBackground(new java.awt.Color(153, 102, 0));
        jLabel46.setFont(new java.awt.Font("Roboto Medium", 1, 12)); // NOI18N
        jLabel46.setForeground(new java.awt.Color(255, 255, 255));
        jLabel46.setText("Warrios of Chaos");
        jPanel2.add(jLabel46, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 290, 110, 20));

        jLabel47.setBackground(new java.awt.Color(153, 102, 0));
        jLabel47.setFont(new java.awt.Font("Roboto Medium", 1, 12)); // NOI18N
        jLabel47.setForeground(new java.awt.Color(255, 255, 255));
        jLabel47.setText("Beastmen");
        jPanel2.add(jLabel47, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 290, 110, 20));

        jLabel48.setBackground(new java.awt.Color(153, 102, 0));
        jLabel48.setFont(new java.awt.Font("Roboto Medium", 1, 12)); // NOI18N
        jLabel48.setForeground(new java.awt.Color(255, 255, 255));
        jLabel48.setText("Skaven");
        jPanel2.add(jLabel48, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 430, 110, 20));

        jLabel49.setBackground(new java.awt.Color(153, 102, 0));
        jLabel49.setFont(new java.awt.Font("Roboto Medium", 1, 12)); // NOI18N
        jLabel49.setForeground(new java.awt.Color(255, 255, 255));
        jLabel49.setText("Chaos Dwarfs");
        jPanel2.add(jLabel49, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 430, 110, 20));

        jLabel50.setBackground(new java.awt.Color(153, 102, 0));
        jLabel50.setFont(new java.awt.Font("Roboto Medium", 1, 12)); // NOI18N
        jLabel50.setForeground(new java.awt.Color(255, 255, 255));
        jLabel50.setText("Greenskins");
        jPanel2.add(jLabel50, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 430, 110, 20));

        jLabel51.setBackground(new java.awt.Color(153, 102, 0));
        jLabel51.setFont(new java.awt.Font("Roboto Medium", 1, 12)); // NOI18N
        jLabel51.setForeground(new java.awt.Color(255, 255, 255));
        jLabel51.setText("Dark Elves");
        jPanel2.add(jLabel51, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 570, 110, 20));

        jLabel52.setBackground(new java.awt.Color(153, 102, 0));
        jLabel52.setFont(new java.awt.Font("Roboto Medium", 1, 12)); // NOI18N
        jLabel52.setForeground(new java.awt.Color(255, 255, 255));
        jLabel52.setText("Ogre Kingdom");
        jPanel2.add(jLabel52, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 570, 110, 20));

        jLabel53.setBackground(new java.awt.Color(153, 102, 0));
        jLabel53.setFont(new java.awt.Font("Roboto Medium", 1, 12)); // NOI18N
        jLabel53.setForeground(new java.awt.Color(255, 255, 255));
        jLabel53.setText("Vampire Coast");
        jPanel2.add(jLabel53, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 570, 110, 20));

        jLabel54.setBackground(new java.awt.Color(153, 102, 0));
        jLabel54.setFont(new java.awt.Font("Roboto Medium", 1, 12)); // NOI18N
        jLabel54.setForeground(new java.awt.Color(255, 255, 255));
        jLabel54.setText("Vampire Counts");
        jPanel2.add(jLabel54, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 570, 110, 20));

        jLabel56.setText("Salir");
        jLabel56.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel56MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel56, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 630, -1, -1));

        jLabel57.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto_final/pngtree-black-silhouette-skull-sign-danger-png-image_5092954.png"))); // NOI18N
        jLabel57.setText("jLabel4");
        jLabel57.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel57MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel57, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 610, 100, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto_final/abismo-infernal-tormento-tierra-fondo-llena-oscuridad-rocas-aterradoras-fuego-ardiente_344451-6225.jpg"))); // NOI18N
        jLabel5.setText("jLabel5");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 1220, 690));

        javax.swing.GroupLayout DecisionLayout = new javax.swing.GroupLayout(Decision.getContentPane());
        Decision.getContentPane().setLayout(DecisionLayout);
        DecisionLayout.setHorizontalGroup(
            DecisionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        DecisionLayout.setVerticalGroup(
            DecisionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel3.setBackground(new java.awt.Color(102, 0, 0));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel60.setBackground(new java.awt.Color(0, 0, 0));
        jLabel60.setFont(new java.awt.Font("Roboto Black", 0, 12)); // NOI18N
        jLabel60.setForeground(new java.awt.Color(0, 0, 0));
        jLabel60.setText(" Mercado");
        jPanel3.add(jLabel60, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 610, -1, -1));

        jLabel61.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto_final/mercado..png"))); // NOI18N
        jLabel61.setText("jLabel61");
        jLabel61.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel61MouseClicked(evt);
            }
        });
        jPanel3.add(jLabel61, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 610, 100, 90));

        MapaGen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto_final/01hw84f2xeb84mja8b4j.jpg"))); // NOI18N
        MapaGen.setText("jLabel31");
        jPanel3.add(MapaGen, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 50, 800, 640));

        MerFalso.setPreferredSize(new java.awt.Dimension(670, 530));

        javax.swing.GroupLayout MerFalsoLayout = new javax.swing.GroupLayout(MerFalso);
        MerFalso.setLayout(MerFalsoLayout);
        MerFalsoLayout.setHorizontalGroup(
            MerFalsoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 670, Short.MAX_VALUE)
        );
        MerFalsoLayout.setVerticalGroup(
            MerFalsoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 530, Short.MAX_VALUE)
        );

        jPanel3.add(MerFalso, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 80, -1, -1));

        jLabel76.setText("Salir");
        jLabel76.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel76MouseClicked(evt);
            }
        });
        jPanel3.add(jLabel76, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 630, -1, -1));

        jLabel77.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto_final/pngtree-black-silhouette-skull-sign-danger-png-image_5092954.png"))); // NOI18N
        jLabel77.setText("jLabel4");
        jLabel77.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel77MouseClicked(evt);
            }
        });
        jPanel3.add(jLabel77, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 610, 100, -1));

        javax.swing.GroupLayout MapaLayout = new javax.swing.GroupLayout(Mapa.getContentPane());
        Mapa.getContentPane().setLayout(MapaLayout);
        MapaLayout.setHorizontalGroup(
            MapaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        MapaLayout.setVerticalGroup(
            MapaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 740, Short.MAX_VALUE)
        );

        jPanel4.setPreferredSize(new java.awt.Dimension(670, 530));

        jPanel5.setBackground(new java.awt.Color(102, 0, 0));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel59.setFont(new java.awt.Font("Roboto Black", 0, 12)); // NOI18N
        jLabel59.setForeground(new java.awt.Color(0, 0, 0));
        jLabel59.setText("Que tal estas Aventurero!!");
        jPanel5.add(jLabel59, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 110, 150, 60));

        jLabel58.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto_final/image (1).png"))); // NOI18N
        jLabel58.setText("jLabel58");
        jPanel5.add(jLabel58, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 70, 190, 150));

        jLabel55.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto_final/mercader.png"))); // NOI18N
        jLabel55.setText("jLabel55");
        jPanel5.add(jLabel55, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 160, 290, 300));

        Comprar.setBackground(new java.awt.Color(153, 0, 0));
        Comprar.setForeground(new java.awt.Color(255, 255, 255));
        Comprar.setText("Comprar Objetos");
        Comprar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComprarActionPerformed(evt);
            }
        });
        jPanel5.add(Comprar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, -1));

        Vender.setBackground(new java.awt.Color(153, 0, 0));
        Vender.setForeground(new java.awt.Color(255, 255, 255));
        Vender.setText("Vender Objetos");
        Vender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VenderActionPerformed(evt);
            }
        });
        jPanel5.add(Vender, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, -1, -1));

        VenderU.setBackground(new java.awt.Color(153, 0, 0));
        VenderU.setForeground(new java.awt.Color(255, 255, 255));
        VenderU.setText("Vender Unidades");
        jPanel5.add(VenderU, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, -1, -1));

        jButton4.setBackground(new java.awt.Color(153, 0, 0));
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("Hacer Alianzas");
        jPanel5.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 60, -1, -1));

        jLabel31.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto_final/pixelcut-export_1.png"))); // NOI18N
        jLabel31.setText("jLabel31");
        jPanel5.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 670, 420));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, 530, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout MercadoAmplioLayout = new javax.swing.GroupLayout(MercadoAmplio.getContentPane());
        MercadoAmplio.getContentPane().setLayout(MercadoAmplioLayout);
        MercadoAmplioLayout.setHorizontalGroup(
            MercadoAmplioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        MercadoAmplioLayout.setVerticalGroup(
            MercadoAmplioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jPanel6.setPreferredSize(new java.awt.Dimension(670, 530));

        jPanel7.setBackground(new java.awt.Color(102, 0, 0));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel62.setFont(new java.awt.Font("Roboto Black", 0, 10)); // NOI18N
        jLabel62.setForeground(new java.awt.Color(0, 0, 0));
        jLabel62.setText("Comprar? A darle Aventurero!!");
        jPanel7.add(jLabel62, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 110, 150, 60));

        jLabel63.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto_final/image (1).png"))); // NOI18N
        jLabel63.setText("jLabel58");
        jPanel7.add(jLabel63, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 70, 190, 150));

        jLabel64.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto_final/mercader.png"))); // NOI18N
        jLabel64.setText("jLabel55");
        jPanel7.add(jLabel64, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 160, 290, 300));

        Armaduras.setBackground(new java.awt.Color(153, 0, 0));
        Armaduras.setForeground(new java.awt.Color(255, 255, 255));
        Armaduras.setText("Armaduras");
        Armaduras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ArmadurasActionPerformed(evt);
            }
        });
        jPanel7.add(Armaduras, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, -1));

        Pociones.setBackground(new java.awt.Color(153, 0, 0));
        Pociones.setForeground(new java.awt.Color(255, 255, 255));
        Pociones.setText("Pociones");
        Pociones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PocionesActionPerformed(evt);
            }
        });
        jPanel7.add(Pociones, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, -1, -1));

        ObMag.setBackground(new java.awt.Color(153, 0, 0));
        ObMag.setForeground(new java.awt.Color(255, 255, 255));
        ObMag.setText("Objetos Magicos");
        ObMag.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ObMagActionPerformed(evt);
            }
        });
        jPanel7.add(ObMag, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, -1, -1));

        ObMit.setBackground(new java.awt.Color(153, 0, 0));
        ObMit.setForeground(new java.awt.Color(255, 255, 255));
        ObMit.setText("Objetos Miticos");
        ObMit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ObMitActionPerformed(evt);
            }
        });
        jPanel7.add(ObMit, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 60, -1, -1));

        Armas.setBackground(new java.awt.Color(153, 0, 0));
        Armas.setForeground(new java.awt.Color(255, 255, 255));
        Armas.setText("Armas");
        Armas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ArmasActionPerformed(evt);
            }
        });
        jPanel7.add(Armas, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 150, -1, -1));

        jPanel8.setBackground(new java.awt.Color(102, 0, 0));

        jLabel66.setText("      /Precios");

        jLabel67.setText("Armaduras = 200");

        jLabel68.setText("Pociones = 150");

        jLabel69.setText("Objetos Mag = 250");

        jLabel70.setText("Objetos Mit = 250");

        jLabel71.setText("Armas = 150");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel66, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel71)
                    .addComponent(jLabel70)
                    .addComponent(jLabel69)
                    .addComponent(jLabel68)
                    .addComponent(jLabel67))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addComponent(jLabel66, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel67)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel68)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel69)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel70)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel71)
                .addGap(0, 82, Short.MAX_VALUE))
        );

        jPanel7.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 210, 150, 250));

        jLabel65.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto_final/pixelcut-export_1.png"))); // NOI18N
        jLabel65.setText("jLabel31");
        jPanel7.add(jLabel65, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 670, 420));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, 530, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout CompObLayout = new javax.swing.GroupLayout(CompOb.getContentPane());
        CompOb.getContentPane().setLayout(CompObLayout);
        CompObLayout.setHorizontalGroup(
            CompObLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        CompObLayout.setVerticalGroup(
            CompObLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jPanel9.setPreferredSize(new java.awt.Dimension(670, 530));

        jPanel10.setBackground(new java.awt.Color(102, 0, 0));
        jPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel72.setFont(new java.awt.Font("Roboto Black", 0, 10)); // NOI18N
        jLabel72.setForeground(new java.awt.Color(0, 0, 0));
        jLabel72.setText("Vender? A darle Aventurero!!");
        jPanel10.add(jLabel72, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 80, 150, 60));

        jLabel73.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto_final/image (1).png"))); // NOI18N
        jLabel73.setText("jLabel58");
        jPanel10.add(jLabel73, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 40, 190, 150));

        jLabel74.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto_final/mercader.png"))); // NOI18N
        jLabel74.setText("jLabel55");
        jPanel10.add(jLabel74, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 160, 290, 300));

        jLabel75.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto_final/mochila.png"))); // NOI18N
        jLabel75.setText("jLabel75");
        jPanel10.add(jLabel75, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 230, 130, 130));

        jPanel11.setBackground(new java.awt.Color(102, 0, 0));

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 360, Short.MAX_VALUE)
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 340, Short.MAX_VALUE)
        );

        jPanel10.add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 90, 360, 340));

        jLabel81.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto_final/pixelcut-export_1.png"))); // NOI18N
        jLabel81.setText("jLabel31");
        jPanel10.add(jLabel81, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 670, 420));

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, 530, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout VendObLayout = new javax.swing.GroupLayout(VendOb.getContentPane());
        VendOb.getContentPane().setLayout(VendObLayout);
        VendObLayout.setHorizontalGroup(
            VendObLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        VendObLayout.setVerticalGroup(
            VendObLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(102, 0, 0));
        jPanel1.setMinimumSize(new java.awt.Dimension(1280, 800));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BtnInicio.setBackground(new java.awt.Color(102, 0, 0));
        BtnInicio.setText("Iniciar Juego");
        BtnInicio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnInicioMouseClicked(evt);
            }
        });
        BtnInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnInicioActionPerformed(evt);
            }
        });
        jPanel1.add(BtnInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 540, 260, 40));

        jLabel3.setText("Salir");
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 630, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto_final/pngtree-black-silhouette-skull-sign-danger-png-image_5092954.png"))); // NOI18N
        jLabel4.setText("jLabel4");
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 610, 100, -1));

        jLabel30.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto_final/logo.png"))); // NOI18N
        jLabel30.setText("jLabel30");
        jPanel1.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 30, 730, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto_final/abismo-infernal-tormento-tierra-fondo-llena-oscuridad-rocas-aterradoras-fuego-ardiente_344451-6225.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 1270, 720));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1288, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 740, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnInicioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnInicioMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_BtnInicioMouseClicked

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "Saliendo del Juego");
        System.exit(0);
    }//GEN-LAST:event_jLabel3MouseClicked

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "Saliendo del Juego");
        System.exit(0);        
    }//GEN-LAST:event_jLabel4MouseClicked
    
    private void BtnInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnInicioActionPerformed
        // TODO add your handling code here:                
        Decision.setVisible(true);
        Decision.setSize(this.getSize());
        
        this.setVisible(false);
    }//GEN-LAST:event_BtnInicioActionPerformed

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        // TODO add your handling code here:                        
    }//GEN-LAST:event_jLabel6MouseClicked

    private void FacSelecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FacSelecActionPerformed
        // TODO add your handling code here:
        String faccionSeleccionada = FacSelec.getText();
        
        boolean existe = false;
        
        for (String faccion : todasFacciones) {
            if (faccion.equalsIgnoreCase(faccionSeleccionada)) {
                existe = true;
                break;
            }
        }

        if (existe) {
            JOptionPane.showMessageDialog(null, "Faccion Seleccionada con Exito");
            Mapa.setVisible(true);
            Mapa.setSize(this.size());
            MerFalso.setVisible(false);
        
            Decision.setVisible(false);
        } else {
            JOptionPane.showMessageDialog(null, "La Faccion Seleccionada no existe");
        }
        
            Random random = new Random();
            recursos = random.nextInt(1001) + 3000; 
            dinero = random.nextInt(601) + 900; 
            ataque = random.nextInt(301) + 400; 
            defensa = random.nextInt(601) + 400;
            poder = random.nextInt(51)+250;
            
            Facciones faccion = new Facciones(faccionSeleccionada, recursos, dinero, ataque, defensa);
            jugador.setRazaSeleccionada(faccion);
            ArrayList<Unidad> unidades = new ArrayList<>();                    
            
                    switch (faccionSeleccionada) {
                        case "The Empire":
                            unidades.add(new Unidad("Hijos de Sigmar",100,40,"Infanteria",poder));
                            unidades.add(new Unidad("Espaderos",90,40,"Infanteria",poder));
                            unidades.add(new Unidad("Herreuelos",40,60,"Caballeria",poder));
                            unidades.add(new Unidad("Gran Cañon",10,80,"Artilleria",poder));
                            unidades.add(new Unidad("Hechiero de la Luz",1,1000,"Mago",poder));
                            break;
                        case "Norsca":
                            unidades.add(new Unidad("Barbaros",100,40,"Infanteria",poder));
                            unidades.add(new Unidad("Berserkers",90,75,"Infanteria",poder));
                            unidades.add(new Unidad("Jinetes Barbaros",40,53,"Caballeria",poder));
                            unidades.add(new Unidad("Carro de Barbaros con Lobos de Hielo",10,78,"Artilleria",poder));
                            unidades.add(new Unidad("Hechicero del Caos",1,1100,"Mago",poder));
                            break;
                        case "Bretonnia":
                            unidades.add(new Unidad("Turba de Campesinos",100,20,"Infanteria",poder));
                            unidades.add(new Unidad("Hombres de armas",90,25,"Infanteria",poder));
                            unidades.add(new Unidad("Guardiaes del Grial",40,160,"Caballeria",poder));
                            unidades.add(new Unidad("Trebuchet Bendecido",10,90,"Artilleria",poder));
                            unidades.add(new Unidad("Profetisa",1,1000,"Mago",poder));
                            break;
                        case "Grand Cathay":
                            unidades.add(new Unidad("Jade Warriors",100,62,"Infanteria",poder));
                            unidades.add(new Unidad("Celestial Dragon Guard",90,80,"Infanteria",poder));
                            unidades.add(new Unidad("Peasant Horsemen",40,100,"Caballeria",poder));
                            unidades.add(new Unidad("Grand Cannon",10,105,"Artilleria",poder));
                            unidades.add(new Unidad("Alchemist",1,1000,"Mago",poder));
                            break;
                        case "Kislev":
                            unidades.add(new Unidad("Tzar Guard",100,57,"Infanteria",poder));
                            unidades.add(new Unidad("Kislevite Warriors",90,60,"Infanteria",poder));
                            unidades.add(new Unidad("Kossovite",40,110,"Caballeria",poder));
                            unidades.add(new Unidad("Little Grom",10,95,"Artilleria",poder));
                            unidades.add(new Unidad("Frost Maiden",1,1000,"Mago",poder));
                            break; 
                        case "Dwarfs":
                            unidades.add(new Unidad("Guerreros Enanos",100,45,"Infanteria",poder));
                            unidades.add(new Unidad("Mineros",90,32,"Infanteria",poder));
                            unidades.add(new Unidad("Girobombardero",40,116,"Caballeria",poder));
                            unidades.add(new Unidad("Lanzaagravios",10,140,"Artilleria",poder));
                            unidades.add(new Unidad("Herrero Runico",1,1000,"Mago",poder));
                            break;                         
                        case "High Elves":
                            unidades.add(new Unidad("Dryads",100,67,"Infanteria",poder));
                            unidades.add(new Unidad("Phoenix Guard",90,70,"Infanteria",poder));
                            unidades.add(new Unidad("Ellyrian Reavers",40,120,"Caballeria",poder));
                            unidades.add(new Unidad("Eagle Claw Bolt Throwers",10,115,"Artilleria",poder));
                            unidades.add(new Unidad("Hand of the Shadow Crown",1,1000,"Mago",poder));
                            break; 
                        case "Wood Elves":
                            unidades.add(new Unidad("Guardias Eternos",100,47,"Infanteria",poder));
                            unidades.add(new Unidad("Guardias Corazon del Invierno",90,80,"Infanteria",poder));
                            unidades.add(new Unidad("Jinetes Salvajes",40,110,"Caballeria",poder));
                            unidades.add(new Unidad("Jinetes de Halcon",10,95,"Artilleria",poder));
                            unidades.add(new Unidad("Cantor de Arboles",1,1000,"Mago",poder));
                            break; 
                        case "Lizardmen":
                            unidades.add(new Unidad("Red Crested Skinks",100,73,"Infanteria",poder));
                            unidades.add(new Unidad("Saurus Warriors",90,71,"Infanteria",poder));
                            unidades.add(new Unidad("Horned Ones",40,131,"Caballeria",poder));
                            unidades.add(new Unidad("Terradon Riders",10,108,"Artilleria",poder));
                            unidades.add(new Unidad("Lord Mazdamundi",1,1000,"Mago",poder));
                            break; 
                        case "Khorne":
                            unidades.add(new Unidad("Forsaken of Khorne",100,68,"Infanteria",poder));
                            unidades.add(new Unidad("Chosen of Khorne",90,110,"Infanteria",poder));
                            unidades.add(new Unidad("Chaos Knights of Khorne",40,121,"Caballeria",poder));
                            unidades.add(new Unidad("Blood Shrine of Khorne",10,135,"Artilleria",poder));
                            unidades.add(new Unidad("Bloodreaper",1,1000,"Mago",poder));
                            break; 
                        case "Nurgle":
                            unidades.add(new Unidad("Nurglings",100,50,"Infanteria",poder));
                            unidades.add(new Unidad("Pestigors",90,65,"Infanteria",poder));
                            unidades.add(new Unidad("Rot Knights",40,104,"Caballeria",poder));
                            unidades.add(new Unidad("Plague Drones of Nurgle",10,95,"Artilleria",poder));
                            unidades.add(new Unidad("Grukmur Three-Horn",1,1000,"Mago",poder));
                            break; 
                        case "Tzeentch":
                            unidades.add(new Unidad("Blue Horrors of Tzeentch",100,47,"Infanteria",poder));
                            unidades.add(new Unidad("Forsaken of Tzeentch",90,80,"Infanteria",poder));
                            unidades.add(new Unidad("Centigors of Tzeentch",40,110,"Caballeria",poder));
                            unidades.add(new Unidad("Exalted Pink Horrors of Tzeentch",10,95,"Artilleria",poder));
                            unidades.add(new Unidad("The Changeling",1,1000,"Mago",poder));
                            break; 
                        case "Slaanesh":
                            unidades.add(new Unidad("Devoted Marauders of Slaanesh",100,65,"Infanteria",poder));
                            unidades.add(new Unidad("Daemonettes of Slaanesh",90,70,"Infanteria",poder));
                            unidades.add(new Unidad("HeartSeekers of Slaanesh",40,110,"Caballeria",poder));
                            unidades.add(new Unidad("Seeker Chariots",10,101,"Artilleria",poder));
                            unidades.add(new Unidad("Cultist of Slaanesh",1,1000,"Mago",poder));
                            break; 
                        case "Warriors of Chaos":
                            unidades.add(new Unidad("Guardia de los Espejos",100,100,"Infanteria",poder));
                            unidades.add(new Unidad("Elegidos",90,140,"Infanteria",poder));
                            unidades.add(new Unidad("Espadas del Caos",40,180,"Caballeria",poder));
                            unidades.add(new Unidad("Alma de la Perdicion",10,140,"Artilleria",poder));
                            unidades.add(new Unidad("Hechicero del Caos",1,1000,"Mago",poder));
                            break; 
                        case "Beastmen":
                            unidades.add(new Unidad("Rebaño de Gors",100,60,"Infanteria",poder));
                            unidades.add(new Unidad("Rebaño de Bestigors",90,100,"Infanteria",poder));
                            unidades.add(new Unidad("Centigors",40,85,"Caballeria",poder));
                            unidades.add(new Unidad("Cigor",10,160,"Artilleria",poder));
                            unidades.add(new Unidad("Chaman del Rebaño",1,1000,"Mago",poder));
                            break; 
                        case "Skaven":
                            unidades.add(new Unidad("Gutter Runners Slingers",100,55,"Infanteria",poder));
                            unidades.add(new Unidad("Death Globe Bombardiers",90,74,"Infanteria",poder));
                            unidades.add(new Unidad("Wolf Rats",40,100,"Caballeria",poder));
                            unidades.add(new Unidad("Plagueclaw Catepults",10,85,"Artilleria",poder));
                            unidades.add(new Unidad("Packmaster",1,1000,"Mago",poder));
                            break; 
                        case "Chaos Dwarfs":
                            unidades.add(new Unidad("Goblin Labourers",100,61,"Infanteria",poder));
                            unidades.add(new Unidad("Infernal Ironsworn",90,78,"Infanteria",poder));
                            unidades.add(new Unidad("Bull Centaur Renders",40,98,"Caballeria",poder));
                            unidades.add(new Unidad("Dreadquake Mortar",10,92,"Artilleria",poder));
                            unidades.add(new Unidad("Gorduz Bakstabber",1,1000,"Mago",poder));
                            break; 
                        case "Greenskins":
                            unidades.add(new Unidad("Guerrero Orkoz",100,45,"Infanteria",poder));
                            unidades.add(new Unidad("Grandotez Orkoz",90,70,"Infanteria",poder));
                            unidades.add(new Unidad("Garrapatos Saltarines de los Goblins Nocturnos",40,65,"Caballeria",poder));
                            unidades.add(new Unidad("Katapulta de Goblins Voladorez",10,90,"Artilleria",poder));
                            unidades.add(new Unidad("Chaman Goblin Nocturno",1,1000,"Mago",poder));
                            break; 
                        case "Dark Elves":
                            unidades.add(new Unidad("Black Ark Corsairs",100,55,"Infanteria",poder));
                            unidades.add(new Unidad("Har Ganeth Executioners",90,84,"Infanteria",poder));
                            unidades.add(new Unidad("Cold One Knights",40,120,"Caballeria",poder));
                            unidades.add(new Unidad("Reaper Bolt Throwers",10,85,"Artilleria",poder));
                            unidades.add(new Unidad("Socreress",1,1000,"Mago",poder));
                            break; 
                        case "Ogre Kingdom":
                            unidades.add(new Unidad("Gnoblar",100,58,"Infanteria",poder));
                            unidades.add(new Unidad("Gnoblars Trappers",90,89,"Infanteria",poder));
                            unidades.add(new Unidad("Mournfang Cavalry",40,102,"Caballeria",poder));
                            unidades.add(new Unidad("Gnoblar Scraplauncher",10,73,"Artilleria",poder));
                            unidades.add(new Unidad("Firebelly",1,1000,"Mago",poder));
                            break;
                        case "Vampire Coast":
                            unidades.add(new Unidad("Zombie Pirate Deckhands Mob",100,57,"Infanteria",poder));
                            unidades.add(new Unidad("Depth Guard",90,92,"Infanteria",poder));
                            unidades.add(new Unidad("Dammed Knights of the Realm",40,113,"Caballeria",poder));
                            unidades.add(new Unidad("Queen Bess",10,101,"Artilleria",poder));
                            unidades.add(new Unidad("Cylostra Direfin",1,1000,"Mago",poder));
                            break; 
                        case "Vampire Counts":
                            unidades.add(new Unidad("Guerreros Esqueletos",100,30,"Infanteria",poder));
                            unidades.add(new Unidad("Guardia de los Tumulos",90,75,"Infanteria",poder));
                            unidades.add(new Unidad("Caballeros Sangrientos",40,170,"Caballeria",poder));
                            unidades.add(new Unidad("Sagrario Mortis",10,90,"Artilleria",poder));
                            unidades.add(new Unidad("Nigromante",1,1000,"Mago",poder));
                            break; 
                        case "Tomb Kings":
                            unidades.add(new Unidad("Skeleton Warrios",100,58,"Infanteria",poder));
                            unidades.add(new Unidad("Tomb Guard",90,76,"Infanteria",poder));
                            unidades.add(new Unidad("Nehehara Horseman",40,103,"Caballeria",poder));
                            unidades.add(new Unidad("Screaming Skulls Catapults",10,105,"Artilleria",poder));
                            unidades.add(new Unidad("Liche Priest",1,1000,"Mago",poder));
                            break;
                        default:
                            System.out.println("Faccion desconocida");
                            break;                        
                    }                    
                    jugador.setUnidades(unidades);
                    
                    for (String faccionNombre : todasFacciones) {
                        if (!faccionNombre.equals(faccionSeleccionada)) {
                            Facciones enemigos = new Facciones(faccionNombre, recursos, dinero, ataque, defensa);
                            facciones.add(enemigos);
                        }
                    }
    }//GEN-LAST:event_FacSelecActionPerformed

    private void jLabel56MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel56MouseClicked
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "Saliendo del Juego");
        System.exit(0);
    }//GEN-LAST:event_jLabel56MouseClicked

    private void jLabel57MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel57MouseClicked
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "Saliendo del Juego");
        System.exit(0);        
    }//GEN-LAST:event_jLabel57MouseClicked

    private void VenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VenderActionPerformed
        // TODO add your handling code here:
        VendOb.setVisible(true);
        VendOb.setLocation(MercadoAmplio.location());
        VendOb.setSize(MercadoAmplio.size()); 
    }//GEN-LAST:event_VenderActionPerformed

    private void jLabel61MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel61MouseClicked
        // TODO add your handling code here:
        MercadoAmplio.setVisible(true);
        MercadoAmplio.setLocation(MerFalso.location());
        MercadoAmplio.setSize(MerFalso.size());
    }//GEN-LAST:event_jLabel61MouseClicked

    private void ComprarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComprarActionPerformed
        // TODO add your handling code here:
        CompOb.setVisible(true);
        CompOb.setLocation(MercadoAmplio.location());
        CompOb.setSize(MercadoAmplio.size());        
    }//GEN-LAST:event_ComprarActionPerformed

    private void ArmadurasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ArmadurasActionPerformed
        // TODO add your handling code here:
        String mensaje = "Compraste Armadura"
                       + "Gastaste = 200" 
                       + "Obtuviste 100 de Defensa";
        String no = "No tiene suficiente dinero"
                       + "Precio = 200" 
                       + "Agrega 100 de Defensa";
        if(jugador.getDinero() < 200){
            JOptionPane.showMessageDialog(null, mensaje);
            jugador.setDinero(jugador.getDinero() - 200);
            jugador.setDefensa(jugador.getDefensa() + 100);
        }else{            
            JOptionPane.showMessageDialog(null, no);
        }
    }//GEN-LAST:event_ArmadurasActionPerformed

    private void PocionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PocionesActionPerformed
        // TODO add your handling code here:
        String mensaje = "Compraste Pociones"
                       + "Gastaste = 150" 
                       + "Obtuviste 25 de Defensa"
                       + "Obtuviste 25 de Ataque";
        String no = "No tiene suficiente dinero"
                       + "Precio = 150" 
                       + "Agrega 25 de Defensa"
                       + "Agrega 25 de Ataque";
        if(jugador.getDinero() < 150){
            JOptionPane.showMessageDialog(null, mensaje);
            jugador.setDinero(jugador.getDinero() - 150);
            jugador.setDefensa(jugador.getDefensa() + 25);
            jugador.setAtaque(jugador.getAtaque() + 25);
        }else{            
            JOptionPane.showMessageDialog(null, no);
        }
    }//GEN-LAST:event_PocionesActionPerformed

    private void ObMagActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ObMagActionPerformed
        // TODO add your handling code here:
        String mensaje = "Compraste Objetos Magicos"
                       + "Gastaste = 250" 
                       + "Obtuviste 50 de Defensa"
                       + "Obtuviste 50 de Ataque";
        String no = "No tiene suficiente dinero"
                       + "Precio = 250" 
                       + "Agrega 50 de Defensa"
                       + "Agrega 50 de Ataque";
        if(jugador.getDinero() < 250){
            JOptionPane.showMessageDialog(null, mensaje);
            jugador.setDinero(jugador.getDinero() - 250);
            jugador.setDefensa(jugador.getDefensa() + 50);
            jugador.setAtaque(jugador.getAtaque() + 50);
        }else{            
            JOptionPane.showMessageDialog(null, no);
        }
    }//GEN-LAST:event_ObMagActionPerformed

    private void ObMitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ObMitActionPerformed
        // TODO add your handling code here:
        String mensaje = "Compraste Objetos Miticos"
                       + "Gastaste = 250" 
                       + "Obtuviste 25 de Defensa"
                       + "Obtuviste 75 de Ataque";
        String no = "No tiene suficiente dinero"
                       + "Precio = 250" 
                       + "Agrega 25 de Defensa"
                       + "Agrega 75 de Ataque";
        if(jugador.getDinero() < 250){
            JOptionPane.showMessageDialog(null, mensaje);
            jugador.setDinero(jugador.getDinero() - 250);
            jugador.setDefensa(jugador.getDefensa() + 25);
            jugador.setAtaque(jugador.getAtaque() + 75);
        }else{            
            JOptionPane.showMessageDialog(null, no);
        }
    }//GEN-LAST:event_ObMitActionPerformed

    private void ArmasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ArmasActionPerformed
        // TODO add your handling code here:
        String mensaje = "Compraste Armas"
                       + "Gastaste = 150" 
                       + "Obtuviste 100 de Ataque";
        String no = "No tiene suficiente dinero"
                       + "Precio = 150" 
                       + "Agrega 100 de Ataque";
        if(jugador.getDinero() < 200){
            JOptionPane.showMessageDialog(null, mensaje);
            jugador.setDinero(jugador.getDinero() - 150);
            jugador.setAtaque(jugador.getAtaque() + 100);
        }else{            
            JOptionPane.showMessageDialog(null, no);
        }
    }//GEN-LAST:event_ArmasActionPerformed

    private void jLabel76MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel76MouseClicked
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "Saliendo del Juego");
        System.exit(0);
    }//GEN-LAST:event_jLabel76MouseClicked

    private void jLabel77MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel77MouseClicked
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "Saliendo del Juego");
        System.exit(0);
    }//GEN-LAST:event_jLabel77MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pantalla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pantalla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pantalla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pantalla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pantalla().setVisible(true);
            }
        });        
        
        ArrayList<Mercado> articulosMercado = new ArrayList<>();
        articulosMercado.add(new Mercado("Objetos mágicos", 10, 100, "Tienda de Magia"));
        articulosMercado.add(new Mercado("Armas", 15, 150, "Armería"));
        articulosMercado.add(new Mercado("Pociones", 20, 50, "Alquimia"));
        articulosMercado.add(new Mercado("Armaduras", 10, 100, "Armería"));
        articulosMercado.add(new Mercado("Piedras Preciosas", 5, 500, "Joyería"));
                
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Armaduras;
    private javax.swing.JButton Armas;
    private javax.swing.JButton BtnInicio;
    private javax.swing.JDialog CompOb;
    private javax.swing.JButton Comprar;
    private javax.swing.JDialog Decision;
    private javax.swing.JTextField FacSelec;
    private javax.swing.JDialog Mapa;
    private javax.swing.JLabel MapaGen;
    private javax.swing.JPanel MerFalso;
    private javax.swing.JDialog MercadoAmplio;
    private javax.swing.JButton ObMag;
    private javax.swing.JButton ObMit;
    private javax.swing.JButton Pociones;
    private javax.swing.JDialog VendOb;
    private javax.swing.JButton Vender;
    private javax.swing.JButton VenderU;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel59;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel60;
    private javax.swing.JLabel jLabel61;
    private javax.swing.JLabel jLabel62;
    private javax.swing.JLabel jLabel63;
    private javax.swing.JLabel jLabel64;
    private javax.swing.JLabel jLabel65;
    private javax.swing.JLabel jLabel66;
    private javax.swing.JLabel jLabel67;
    private javax.swing.JLabel jLabel68;
    private javax.swing.JLabel jLabel69;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel70;
    private javax.swing.JLabel jLabel71;
    private javax.swing.JLabel jLabel72;
    private javax.swing.JLabel jLabel73;
    private javax.swing.JLabel jLabel74;
    private javax.swing.JLabel jLabel75;
    private javax.swing.JLabel jLabel76;
    private javax.swing.JLabel jLabel77;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel81;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    // End of variables declaration//GEN-END:variables
    static Random random = new Random();
    static Jugador jugador = new Jugador();
    static Inventario inventario = new Inventario ();
    static ArrayList<Facciones> facciones = new ArrayList<>();
    static ArrayList<Facciones> enemigos = new ArrayList<>();
    static String [] todasFacciones = {
        "The Empire", "Norsca", "Bretonnia", "Grand Cathay", "Kislev",
        "Dwarfs", "High Elves", "Wood Elves", "Lizardmen", "Khorne",
        "Nurgle", "Tzeentch", "Slaanesh", "Warriors of Chaos", "Beastmen",
        "Skaven", "Chaos Dwarfs", "Greenskins", "Dark Elves", "Ogre Kingdom",
        "Vampire Coast", "Vampire Counts", "Tomb Kings"
    };
    static int recursos;
    static int dinero;
    static int ataque;
    static int defensa;
    static int poder;

    private void Continuar(Jugador jugador, Inventario inventario) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
